### ISSUE TITLE
collector-http connection error log is too verbose 

### ISSUE THREAD

**Issue by posener** [openzipkin/zipkin-go-opentracing#41]
When upstream server is causing client errors on `c.client.Do`, `HTTPCollector` logs an error on every request that fails.

To my opinion this is too verbose. The client may have a state and can log only when the state changes.
This is clear enough and don't cause log spamming when upstream server is in error state.

Please give your opinion on this.

Cheers

**Comment by adriancole** [comment]
@posener wingtips from nike (@nicmunroe) has an interesting approach, which is to log error on interval with a sample of the error. For example, instead of logging a variable rate, budget for one log message per minute. This would keep the logs from getting full, but still allow someone to know the status. This is a variant on the "log once" pattern, except takes into account that the backend can resolve at some point.

**Comment by posener** [comment]
Thanks, I must say I prefer the log once every state change approach: it will log when the backend fails, but it will also log when the state goes from error to passing. you don't actually need more than that.

**Comment by adriancole** [comment]
ack. was just food for thought

**Comment by basvanbeek** [comment]
I prefer a solution where we have a rate limit on the amount of same log errors (interval based de-duping with an occurrence counter for each time window).

For now I'll keep as is and wait for this to become a more popular topic.

**Comment by basvanbeek** [comment]
closing due to no traffic.
