### ISSUE TITLE
textMapPropagator breaks span after inject

### ISSUE THREAD

**Issue by mkabischev** [openzipkin/zipkin-go-opentracing#6]
Hi. Seems that textMapPropagator breaks span after it being injected
https://github.com/openzipkin/zipkin-go-opentracing/blob/master/propagation_ot.go#L54
```go
carrier.Set(zipkinTraceID, strconv.FormatUint(sc.raw.TraceID, 16))
	carrier.Set(zipkinSpanID, strconv.FormatUint(sc.raw.SpanID, 16))
	if !p.tracer.options.clientServerSameSpan {
		sc.raw.ParentSpanID = 0
	}
	carrier.Set(zipkinParentSpanID, strconv.FormatUint(sc.raw.ParentSpanID, 16))
	carrier.Set(zipkinSampled, strconv.FormatBool(sc.raw.Sampled))
```
sc is pointer, so if clientServerSameSpan option is equal false (it`s equal to false by default) then we remove parentSpanID from this span.

Comparing with https://github.com/openzipkin/zipkin-go-opentracing/blob/master/propagation.go#L36 there parentSpanID=0 is only passed to carrier, so it doesn`t affect span.

This error can be reproduced if request depth is more then 2:
```
service1 (spanID: 1, parentSpanID: 0) -> service2 (spanID: 2, parentSpanID: 1)
service1 (spanID: 1, parentSpanID: 0) -> service2 (spanID: 3, parentSpanID: 1)
service2 (spanID: 3, parentSpanID: 1) -> service3 (spanID: 4, parentSpanID: 3)
```
But after injecting spanID:3 it`s parentID becomes 0 and it becomes root span like as spanID.

I can send PR for fix this issue if you want.

**Comment by drscre** [comment]
To put is short

Currently, [Inject()](https://github.com/openzipkin/zipkin-go-opentracing/blob/master/propagation_ot.go#L54) *modifies* the original span by setting [ParentSpanID = 0](https://github.com/openzipkin/zipkin-go-opentracing/blob/master/propagation_ot.go#L54) on the span object (since span is passed as a pointer).

Because if this, span.Finish() sends broken span to zipkin.

Inject() *must not modify* the original span object, and thats what [PR-7](https://github.com/openzipkin/zipkin-go-opentracing/pull/7 is about) is about

**Comment by basvanbeek** [comment]
This will be fixed on Monday adding proper support for flags too.

**Comment by mkabischev** [comment]
@basvanbeek, thanks!
