### ISSUE TITLE
Activating ClientServerSameSpan resulted in duplicated binnary annotations

### ISSUE THREAD

**Issue by embs** [openzipkin/zipkin-go-opentracing#81]
Setting

```go
zipkin.ClientServerSameSpan(true)
```

in https://github.com/microservices-demo/user/pull/53 caused the shared span to come up with duplicated `http.method` and `http.url` binnary annotations (fames marked with 3 in figure below):

![img](https://user-images.githubusercontent.com/1200033/30696853-69c93304-9eb3-11e7-8354-8cafcc98de35.png)

Is there a way to make the tracer not to add annotations if their keys are already present in the span?

Thanks!

**Comment by adriancole** [comment]
It can't know if there's something already in the span (from another node).
This is basically a UI concern. this one.. right?
https://github.com/openzipkin/zipkin/issues/989

**Comment by embs** [comment]
Thanks, @adriancole.

I wonder why there are no duplicated binary annotations for traces between Java <-> Java (instrumented with sleuth) services interactions which are also sharing span (at least as I can tell):

![selection_004](https://user-images.githubusercontent.com/1200033/30705832-f39f99ba-9ecc-11e7-8809-a9ecd80f5d93.png)

This span (managed by sleuth) doesn't seem to be in accordance with this [assertion](https://github.com/openzipkin/zipkin/issues/963#issue-133014655):

> At least htrace, opentracing, google cloud trace and sleuth use single-host spans.

As it looks like that both nodes are writing to the same span.

Do you know how sleuth manages not to adding dupes into the bin annotations?

**Comment by adriancole** [comment]
Some avoid dupes by only writing certain tags on client and others on
server.

The key here is that if there are dupes with same value we can dedupe them
in javascript.

About single host span, it is still common in zipkin to have client and
server write the same ID. This makes the span detail easy as you see
complete rpc in one pane.

Duplication is a known issue and can be killed in probably less time than
discussing it :)

The different values here are largely due to a bug where one tracer is only
writing the path for the http.url tag (we have http.path tag)

**Comment by embs** [comment]
Thank you again for the clarifications, @adriancole.

Then I'm closing this issue as

1. Duplicated annotations keys is not a real problem
2. https://github.com/openzipkin/zipkin/issues/989 exists for handling duplication within UI

As per

> The different values here are largely due to a bug where one tracer is only writing the path for the http.url tag (we have http.path tag)

I'm aware that the wrong value is being written by the go instrumentation code but I'm not sure in which part of it the bug lives. I'll try and file an issue as soon as I discover it out.
